### ISSUE TITLE
发现一个类名写错了或者是少写一个类

### ISSUE THREAD

**Issue by maxing1005** [kollway-app/wechat-pay#1]
![default](https://cloud.githubusercontent.com/assets/23148463/26049161/a3e60a4e-398c-11e7-9287-998135aff449.png)
路径是：WeChat.php 中的122行左右，错误类是UnifiedOrder，报错是没有该类

**Comment by kollway-app** [comment]
1.0.0的版本已经停止维护了，可以使用devmaster的版本
