### ISSUE TITLE
是不是缺少两个类？

### ISSUE THREAD

**Issue by maxing1005** [kollway-app/wechat-pay#2]
缺少UnifiedOrder类和 BaseAbstract类，不过还是谢谢你的代码。注：我不是来找茬，我是来请教的，请大神不吝赐教啊！
![1](https://cloud.githubusercontent.com/assets/23148463/26052919/8907ae0a-3999-11e7-9f68-b01eda645041.png)

**Comment by kollway-app** [comment]
统一下单调用Wechat.php里的unifiedOrder()方法，传入两个参数，第一个参数是WxPayUnifiedOrder的实例，第二个参数是timeout值。
WxPayUnifiedOrder类在src/Kollway/WechatPay包下

**Comment by maxing1005** [comment]
![default](https://cloud.githubusercontent.com/assets/23148463/26085808/5a29bbde-3a19-11e7-86eb-b4ab39da816b.png)
那这里该怎么改呢？是这样吗？我没有在WxPayUnifiedOrder类中发现add方法。是要这样改吗？
![2](https://cloud.githubusercontent.com/assets/23148463/26085893/f5136078-3a19-11e7-85ef-37681f674d61.png)
谢谢告知！

**Comment by maxing1005** [comment]
![2](https://cloud.githubusercontent.com/assets/23148463/26085909/127a52fc-3a1a-11e7-99c3-f169a7c36b06.png)
刚才第二张图片发错了

**Comment by maxing1005** [comment]
收到您的回复，我很开心。但是我还是不太明白，我该了一点您能帮我看看是修改这里就可以了吗？附件是我修改的代码的截图。请尽快给我答复，谢谢。
![Uploading   ##P8ESPSKKS1SFIBOPN{~W04Y.png…]()

**Comment by maxing1005** [comment]
图片如果加载不出来，可以看看代码（后四行）：
 $params = compact('out_trade_no', 'device_info', 'body', 'total_fee', 'spbill_create_ip', 'notify_url', 'trade_type');
        $params = array_merge($params, [
            'appid' => $this->appId,
            'mch_id' => $this->mchId,
            'out_trade_no' =>'11125288',
        ]);
       $wxPU = new WxPayUnifiedOrder();
        $uO = new Wechat();
        $unifiedOrder = $uO->UnifiedOrder($wxPU,6);
        return $unifiedOrder;
    }

**Comment by kollway-app** [comment]
你的$params并没有真正使用到啊，另外$wxPU对象里有几个必填属性，详情请查阅源码里的注释
